app/urls.py
from django.contrib import admin
from django.urls import path,include
from rifa.views import home
from django.conf import settings
from django.conf.urls.static import static
import os
from app.settings import BASE_DIR

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = 'home'),
    path('rifa/', include('rifa.urls')),
    path('pagamento/', include('pagamento.urls')),
    path('usuario/', include('usuario.urls')),
    path('accounts/', include('allauth.urls')),  # Inclua esta linha para as URLs do django-allauth
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static('/usuario/static/', document_root=os.path.join(BASE_DIR, 'usuario/static'))
    urlpatterns += static('/rifa/static/', document_root=os.path.join(BASE_DIR, 'rifa/static'))
    urlpatterns += static('/pagamento/static/', document_root=os.path.join(BASE_DIR, 'pagamento/static'))

rifa/urls.py
from django.urls import path

from . import views

app_name = 'rifa'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('nova_rifa', views.nova_rifa, name = 'nova_rifa'),
    path('edit_rifa/<int:rifa_id>/<int:id>', views.edit_rifa, name = 'edit_rifa'),
    path('<int:id>/<str:context>/', views.rifa, name='rifa'),
    path('<int:id>/', views.rifa, name='rifa'), 
    
]

usuario/urls.py
from django.urls import path

from . import views

app_name = 'usuario'

urlpatterns = [
    path('', views.cadastro, name='cadastro'),
    path('login/', views.login, name='login'),
    
]

templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
    {% block head %}
<head>
    
    <script src="{% static 'rifa/js/jquery-3.7.1.min.js' %}" type="text/javascript"></script> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{% endblock title%}</title>
    <link href="{% static 'rifa/css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'rifa/css/style.css' %}">
    <script src="{% static 'rifa/js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'rifa/js/js.js' %}" type="text/javascript"></script>
    <script src="{% static 'pagamento/pagamento.js' %}"></script>
</head>
{% endblock head %}
<body>
    <div class="conteudo">
        <div class="rifa">
            <nav class="navbar bg-body-tertiary info-box">
                <div class="container">
                  <a class="navbar-brand" href="#">
                    <img src="{% static 'icon.png' %}" alt="ìcone" width="30" height="24">
                  </a>
                  <ul class="nav justify-content-end">
                    <li class="nav-item">
                      <a style="text-decoration: none;" class="nav-link" aria-current="page" href="{%url 'rifa:home'%}" title="Início">
                        
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="24" fill="currentColor" class="bi bi-house-heart" viewBox="0 0 16 16">
                            <path d="M8 6.982C9.664 5.309 13.825 8.236 8 12 2.175 8.236 6.336 5.309 8 6.982"/>
                            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.707L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.646a.5.5 0 0 0 .708-.707L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
                        </svg>
        
                      </a>
                    </li>
                    <li class="nav-item">
                        <a style="text-decoration: none;" class="nav-link" aria-current="page" href="{%url 'rifa:nova_rifa'%}" title="Criar Rifa">
                          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="24" fill="currentColor" class="bi bi-ticket-perforated" viewBox="0 0 16 16">
                              <path d="M4 4.85v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9z"/>
                              <path d="M1.5 3A1.5 1.5 0 0 0 0 4.5V6a.5.5 0 0 0 .5.5 1.5 1.5 0 1 1 0 3 .5.5 0 0 0-.5.5v1.5A1.5 1.5 0 0 0 1.5 13h13a1.5 1.5 0 0 0 1.5-1.5V10a.5.5 0 0 0-.5-.5 1.5 1.5 0 0 1 0-3A.5.5 0 0 0 16 6V4.5A1.5 1.5 0 0 0 14.5 3zM1 4.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v1.05a2.5 2.5 0 0 0 0 4.9v1.05a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-1.05a2.5 2.5 0 0 0 0-4.9z"/>
                          </svg>
                        </a>
                    </li>
                     
                    <li class="nav-item">
                      <a style="text-decoration: none;" class="nav-link" href="{%url 'usuario:login'%}" title="Entrar">
        
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="24" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                            <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                        </svg>
                    </a>
                    </li>           
                    <li class="nav-item">
                      <a style="text-decoration: none;" class="nav-link" href="javascript:void(0)" onclick="share()" title="Compartilhar">
                        
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="24" fill="currentColor" class="bi bi-share" viewBox="0 0 16 16">
                            <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.5 2.5 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5m-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3"/>
                        </svg>
                    </a>
                    </li>
                    <li class="nav-item">
                      <a style="text-decoration: none;" class="nav-link" href="#" title="Configurações">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="24" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
                          <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492M5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0"/>
                          <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115z"/>
                        </svg>
                      </a>
                    </li>
                  </ul>
                </div>
              </nav>   
    {% block content%}
    
    {% endblock content%}
        </div>
    </div>   
</body>
</html>